version: '3.9'

services:
# application service
  flask_app:
    container_name: flask_app
    image: flask_app:1.0.0
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb://mongo_db/test_database
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - custom
    depends_on:
      - mongo_db

  # database service
  mongo_db:
      image: mongo
      container_name: "mongo_db"
      ports:
        - "27017:27017"
      networks:
        - custom
networks:
  custom:
    driver: bridge